<link rel="stylesheet" type="text/css" href="/assets/css/bootstrap-datetimepicker.min.css">
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
                <h2>Enturmar Catequizando</h2>
                <span style="color:#ff0000">Atenção! Somente após preenchimento dos campos, a opção salvar será habilitada</span>
            </div>

            <?php
            $form->setAttribute('action', $this->url('navegacao', array('controller' => $controller, 'action' => 'gravar')));
            $form->setAttribute('method', 'post');
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('data-toggle', 'validator');
            $form->prepare();
            echo $this->form()->openTag($form);

            $form->get('id_usuario')->setValue($this->Auth()->id_usuario);
            echo $this->formHidden($form->get('id_usuario'));

            #Alysson - TODO: Alterar este ID FIXO pelo ID do catequizando Selecionado
            $form->get('id_catequizando')->setValue(2);

            #Recuperando o Nome do Catequizando Pelo ID e Setando no Formulario
            $catequizando = new \Catequizando\Service\CatequizandoService();
            $arrCatequizando = $catequizando->getCatequizandoToArray($form->get('id_catequizando')->getValue());
            $form->setData(['id_catequizando' => $arrCatequizando['nm_catequizando']]);

            ?>

            <hr>
            <fieldset>
                <div class="container">
                    <div class="row">
                        <div class="col-sm-2">
                            <div class="form form-group">

                                <?= $this->formRow($form->get('id_turma')) ?>                            </div>
                        </div>
                        <div class="col-sm-1"></div>
                        <div class="col-sm-2">
                            <div class="form form-group">
                                <?= $this->formRow($form->get('id_periodo_letivo')) ?>
                            </div>
                        </div>
                        <div class="col-sm-1"></div>
                        <div class="col-sm-2">
                            <div class="form form-group">
                                <?= $this->formRow($form->get('nr_sala')) ?>
                            </div>
                        </div>
                        <div class="col-sm-1"></div>
                        <div class="col-sm-3">
                            <div class="form form-group">
                                <?= $this->formRow($form->get('id_catequizando')) ?>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form form-group">
                                <?= $this->formRow($form->get('tx_observacoes')) ?>
                            </div>
                        </div>
                    </div>

                </div>
            </fieldset>

            <div class="form-group">
                <div class="col-md-10">
                    <a id="enturmar_catequizando" class="btn btn-primary" href="#" title="Adicionar data do encontro">Salvar</a>
                    <a href="<?= $this->url('navegacao', ['controller' => $controller]) ?>" class="btn btn-default">Voltar</a>
                </div>
            </div>

            <div class="row" id="turmacatequizando-pagination"></div>


            <?= $this->form()->closeTag(); ?>
        </div>
    </div>

</div>
<script type="text/javascript"
        src="/assets/compact-js/moment.js,bootstrap-datetimepicker.min.js,validator.min.js,jquery.mask.min.js,jquery.complexify.js,usuario|usuario|cadastro.js"></script>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function () {
        //Autocomplete Catequiizandos - Eduardo Ferreira
        $("#id_catequizando").autocomplete({
            minLength:3,
            source:"/catequizando-catequizando/autocompletecatequizando"
        });

        $('#enturmar_catequizando').hide();
        $("#id_catequizando").val("");
        function carregaralunosTurmaAposInserir() {
            <?php
            if( (isset($id_turma) && $id_turma) && (isset($id_periodo_letivo) && $id_periodo_letivo) ) { ?>
            id_turma = <?=$id_turma?>;
            id_periodo_letivo = <?=$id_periodo_letivo?>;
            if (id_turma && id_periodo_letivo) {
                carregarListaCatequizandosTurmaAjax(id_turma, id_periodo_letivo); //Chama a Paginação da listagem
            }
            <?php
            }
            ?>
        }

        //Função que faz a listagem ser paginada.
        function carregarListaCatequizandosTurmaAjax(id_turma, id_periodo_letivo) {
            $('#enturmar_catequizando').show();

            $.ajax({
                type: "post",
                dataType: "text",
                cache: false,
                url: '/turma_catequizando-turmacatequizando/detalhe-pagination',
                async: true,
                data: {
                    id_turma: id_turma,
                    id_periodo_letivo: id_periodo_letivo
                },
                beforeSend: function () {
                    $('#turmacatequizando-pagination').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                    );
                },
                success: function (data) {
                    $('#turmacatequizando-pagination').html(data);
                }
            });
        }

        //Realiza a chamada Ajax, caso os dois combos estejam preenchidos
        $('#id_turma').change(function () {
            id_turma = $(this).val();
            id_periodo_letivo = $('#id_periodo_letivo').val();
            if (id_turma && id_periodo_letivo) {
                carregarListaCatequizandosTurmaAjax(id_turma, id_periodo_letivo);//Chama a Paginação da listagem
            } else {
                $('#turmacatequizando-pagination').html(
                    '<div class="row"><div class="col-md-12 text-center"></div></div>'
                );
            }
        });

        //Realiza a chamada Ajax, caso os dois combos estejam preenchidos
        $('#id_periodo_letivo').change(function () {
            id_turma = $('#id_turma').val();
            id_periodo_letivo = $(this).val();
            if (id_turma && id_periodo_letivo) {
                carregarListaCatequizandosTurmaAjax(id_turma, id_periodo_letivo);//Chama a Paginação da listagem
            } else {
                $('#turmacatequizando-pagination').html(
                    '<div class="row"><div class="col-md-12 text-center"></div></div>'
                );
            }
        });

        //Função Ajax que adiciona alunos a uma determinada turma
        $('#enturmar_catequizando').click(function () {
            var dados = $('#turmacatequizandoform').serialize();
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: '/turma_catequizando-turmacatequizando/enturmar-aluno',
                async: true,
                data: dados,
                success: function (response) {
                    $("#id_turma").val("");
                    $("#id_periodo_letivo").val("");
                    //$("#id_catequizando").val(""); //Alysson - TODO: remover o comentario depois que o catequista estiver Implementado
                    $("#tx_observacoes").val("");

                    //Caso a insersao tenha sido realizada com sucesso
                    if (response.sucesso == true) {
                        //carrego a lista apenas com os alunos da turma
                        carregarListaCatequizandosTurmaAjax(response.id_turma, response.id_periodo_letivo);//Chama a Paginação da listagem
                        $("#id_turma").val(response.id_turma); //Deixo setado a turma
                        $("#id_periodo_letivo").val(response.id_periodo_letivo); //Deixo setado o periodo letivo
                    }
                }
            });

            return false;
        });

        carregaralunosTurmaAposInserir();

    });
</script>