<div class="page-head">
    <h2>Cadastro de Sacramentos do Catequisando</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
                <?php
                $form->setAttribute('action', $this->url('navegacao', array('controller' => $controller, 'action' => 'gravar')));
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('method', 'post');
                $form->setAttribute('data-role', 'form');
                $form->prepare();
                echo $this->form()->openTag($form);
                $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue()));

                echo $this->formHidden($form->get('id'));

                #Recuperando o Nome do Catequisando Pelo ID e Setando no Formulario
                #$catequisando = new \Catequisando\Service\CatequisandoService();
                #$arrCatequisando = $catequisando->getCatequisandoToArray($form->get('id_catequisando')->getValue());
                #$form->setData(['id_catequisando' => $arrCatequisando['nm_catequisando']]);

                ?>
                <div class="form-group">
                    <div class="col-md-4">
                        <?= $this->formRow($form->get('id_catequisando')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?= $this->formRow($form->get('id_sacramento')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?= $this->formRow($form->get('id_paroquia')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <?= $this->formRow($form->get('cs_comprovante_batismo')) ?>
                        <div class="help-block with-errors">

                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="<?= $this->url('navegacao', ['controller' => $controller]) ?>" class="btn btn-default">Voltar</a>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript"
        src="/assets/compact-js/moment.js,bootstrap-datetimepicker.min.js,validator.min.js,jquery.mask.min.js,jquery.complexify.js,usuario|usuario|cadastro.js"></script>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function () {
        $("input#id_catequisando").autocomplete({
            minLength: 4,
            source: "/catequisando-catequisando/autocompletecatequisando"
        });
    });
  </script>