<?php
  /** @var $lista \Principal\Service\Principal[] */
?>
<div class="page-head">
    <div class="container">
        <div align="center">
            <h3>Navegação Rápida</h3>
            <p>Escolha pra onde deseja ir.</p>
        </div>
    </div>

</div>

<br /><br /><br /><br /><br /><br /><br /><br /><br />



<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function() {
        $('#competicao').click(function(){
            href = 'evento-evento';
            window.location.href = href;
        });
        $('#academias').click(function(){
            href = 'academia-academia';
            window.location.href = href;
        });
        $('#inscricao').click(function(){
            href = 'inscricoes_evento-inscricoesevento';
            window.location.href = href;
        });
        $('#chavesdeluta').click(function(){
            href = 'chaves_luta-chavesluta';
            window.location.href = href;
        });
    });
</script>