
<div class="row row-offcanvas row-offcanvas-right">
    <div class="col-xs-12 col-sm-9">    

            <div class = "well">
                <div class = "page-head">
                    <h2>Atualização de dados cadastrais</h2>
                </div>

                <dl>
                    <dt>Alterar senha:</dt>
                    <dd>
                        <a href = "/usuario-usuario/alterar-senha">Click aqui para alterar sua senha</a>
                    </dd>
                </dl>

                <dl>
                    <dt>Nome Completo:</dt>
                    <dd><?= ucwords($usuario['nm_usuario'])
                        ?></dd>
                </dl>        

                <dl>
                    <dt>E-mail: </dt>
                    <dd><?= $form->get('em_email')->getValue(); ?></dd>
                </dl>
                <?php
                $form->setAttribute('action', $this->url('navegacao', array('controller' => $controller, 'action' => 'gravar-atualizacao')));
                $form->setAttribute('method', 'post');
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('data-toggle', 'validator');
                $form->prepare();
                echo $this->form()->openTag($form);
                ?>
                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('id_sexo')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-6">
                        <?= $this->formRow($form->get('nr_telefone')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>

                <hr />
                <div class="form-group">                    
                    <div class="col-md-6">
                        <button type="submit" class="btn btn-primary">Salvar</button>

<!--                        <a href="--><?//= $this->url('navegacao', array('controller' => 'mcnetwork-index', 'action' => 'index')) ?><!--" class="btn btn-default">Voltar</a>                    -->
<!--                        Alysson -->
                        <a href="<?= $this->url('navegacao', array('controller' => 'usuario-index', 'action' => 'index')) ?>" class="btn btn-default">Voltar</a>
                    </div>
                </div>

                <?= $this->form()->closeTag(); ?>
            </div>
    </div>
    <?=
    $this->partial('partials/menu-left', [
        'auth' => $auth,
        'contratoEntity' => $contratoEntity,
        'configList' => $configList,
        'meusGanhosList' => $meusGanhosList,
    ]);
    ?>

</div>
<script type="text/javascript" src="/assets/compact-js/validator.min.js,jquery.mask.min.js,usuario|usuario|atualizar-dados.js"></script>