<link href="/assets/css/usuario/usuario/cadastro.css" rel="stylesheet" />
<?php
if ($temPendenciaCadastral) {
    ?>
    <div class="bs-callout bs-callout-danger">
        Você tem pêndencias cadastrais. <a href="/usuario-usuario/atualizar-dados">Clique aqui para atualizar seus dados</a>
    </div>
    <?php
} else {

    if ($temSaqueComReciboEnviado) {
        ?>
        <div class="bs-callout bs-callout-info">
            Quando você envia um recibo de bônus, não é possível realizar atualizações cadastrais.
        </div>
        <?php
    } else {
        ?>
        <div class="bs-callout bs-callout-info">
            <a href="/usuario-usuario/atualizar-dados">Clique aqui para atualizar seus dados</a>
        </div>
        <?php
    }
}
?>
<br />
<h4>&nbsp;&nbsp;&nbsp;&nbsp;Dados Pessoais</h4>
<table class="table table-striped">
    <tbody>
    <tr>
        <td style="width: 30%"><h6><b class="pull-right">Nome Completo: </b></h6></td><td><h6><?= ucwords($usuario['nm_usuario']) ?></h6></td>
    </tr>

    <tr>
        <td><h6><b class="pull-right">Telefone: </b></h6></td><td><h6><?= \Estrutura\Helpers\Telefone::telefoneMask($usuario['nr_ddd_telefone'] . $usuario['nr_telefone']) ?></h6></td>
    </tr>

    <tr>
        <td><h6><b class="pull-right">E-mail: </b></h6></td><td><h6><?= $usuario['em_email'] ?></h6></td>
    </tr>
    </tbody>
</table>
