<link rel="stylesheet" type="text/css" href="/assets/css/bootstrap-datetimepicker.min.css" >
<div class="row row-offcanvas row-offcanvas-right">
    <div class="col-md-12">

            <div class="page-head">
                <h2>Cadastro</h2>
            </div>
            <fieldset>
                <legend>Dados do Catequizando</legend>
                <?php if(isset($catequizando) && !empty($catequizando)){ ?>
                    <div class="bs-callout bs-callout-info">
                        <ul class="primary">
                            <li><b>Catequizando:</b> <?=$catequizando->getNmCatequizando()?></li>
                            <li><b>Idade:</b> <?=\Estrutura\Helpers\Data::calcularIdadeDoAtleta($catequizando->getDtNascimento())?></li>

                        </ul>
                    </div>
                <?php } ?>
            </fieldset>

            <?php
            $form->setAttribute('action', $this->url('navegacao', array('controller' => $controller, 'action' => 'gravar')));
            $form->setAttribute('method', 'post');
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('data-toggle', 'validator');
            $form->setAttribute('class','col-md-12');
            $form->prepare();
            echo $this->form()->openTag($form);
            $form->get('id_catequizando')->setValue(Estrutura\Helpers\Cript::enc($catequizando->getId()));
            echo $this->formHidden($form->get('id_catequizando'));
            ?>

            <br />
            <div class="row">
                <div class="form-group">
                    <div class="col-md-5">
                        <?= $this->formRow($form->get('nm_responsavel')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-5">
                        <?= $this->formRow($form->get('id_sexo')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                 </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-5">
                        <?= $this->formRow($form->get('id_telefone_residencial')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-5">
                        <?= $this->formRow($form->get('id_telefone_celular')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-5">
                        <?= $this->formRow($form->get('em_email_confirm')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-5">
                        <?= $this->formRow($form->get('em_email')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <div class="col-md-5">
                        <?= $this->formRow($form->get('id_situacao')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-5">
                        <?= $this->formRow($form->get('id_movimento_pastoral')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-5">
                        <?= $this->formRow($form->get('id_profissao')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-5">
                        <?= $this->formRow($form->get('cs_participa_movimento_pastoral')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="form-group">
                    <div class="col-md-5">
                        <?= $this->formRow($form->get('id_situacao_conjugal')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="col-md-1"></div>
                    <div class="col-md-5">
                        <?= $this->formRow($form->get('id_grau_parentesco')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="form-group">
                    <div class="col-md-5">
                        <?= $this->formRow($form->get('tx_observacao')) ?>
                        <div class="help-block with-errors"></div>
                    </div>
                    <div class="col-md-1"></div>
            </div>

                <div class="help-block with-errors"></div>
            </div>

            <div class="row">
                <div class="form-group">
                    <div class="col-md-10">
                        <button id="adicionar" class="btn btn-primary">Adicionar</button>
                    </div>
                </div>
            </div>

        <hr/>
            <?= $this->form()->closeTag(); ?>

        <div class="row">
            <div class="col-md-12" id="responsavel-pagination"></div>
        </div>

        </div>

    </div>

<script type="text/javascript" src="/assets/compact-js/moment.js,bootstrap-datetimepicker.min.js,validator.min.js,jquery.mask.min.js,jquery.complexify.js,usuario|usuario|cadastro.js"></script>
<script>
    $(document).ready(function() {


        //Função que faz a listagem ser paginada.
        function carregarGridPaginadaAjax(){
            $.ajax({
                type: "POST",
                dataType: "text",
                cache: false,
                url: '/catequizando-catequizando/catequizandoResponsavelPagination',
                async: true,
                data: {id_catequizando:2},
                beforeSend: function () {
                    $('#responsavel-pagination').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                    );
                },
                success: function (data) {
                    $('#responsavel-pagination').html(data);
                }
            });
        }
        carregarGridPaginadaAjax(); //Chama a Paginação da listagem

        /*Botao Adicionar */
        $('#adicionar').click(function(){
            var dados = $('#catequizandoresponsavelform').serialize();
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: '/catequizando-catequizando/addResponsavelViaCadastro',
                async: true,
                data: dados,
                success: function(response) {

                    if(response.sucesso == true){
                        carregarGridPaginadaAjax();
                    }
                }
            });

            return false;
        });

    });
</script>