<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<!--<link rel="stylesheet" href="/assets/css/jquery.tablesorter.theme.bootstrap.css">-->
<!--<link rel="stylesheet" href="/assets/css/jquery.tablesorter.pager.css">-->


<?php
/** @var $form \Graduacao\Form\Graduacao */
/** @var $lista \Graduacao\Service\Graduacao[] */
?>
<div class="page-head">
    <h2>Lista de Graduações</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?= $this->url('navegacao', array('controller' => $controller, 'action' => 'cadastro')) ?>" title="Adicione nova graduacao">Nova Graduação</a>
        </div>
    </div>
    <br />
    <div class="row" id="index-pagination"></div>
</div>

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/graduacao-graduacao/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#index-pagination').html(
                    '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                );
            },
            success: function (data) {

                $('#index-pagination').html(data);
            }
        });

    })
</script>