<link rel="stylesheet" href="/assets/css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<div class="page-head">
    <h2>Lista de Profissões</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default"
               href="<?= $this->url('navegacao', array('controller' => $controller, 'action' => 'cadastro')) ?>"
               title="Nova Profissão">Cadastrar Profissão</a>
        </div>
    </div>
    <br/>
    <div class="row" id="profissao-pagination"></div>
</div>

<script>
    // funcao ajax para buscar a paginacao
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/profissao-profissao/index-pagination',
            async: true,
            data: {},
            beforeSend: function () {

                $('#profissao-pagination').html(
                    '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                );
            },
            success: function (data) {

                $('#profissao-pagination').html(data);
            }
        });

    })
</script>
