<div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>

    <!--    <a class="navbar-brand" href="/mcnetwork-index" style="padding-top: 0px;">-->
    <a class="navbar-brand" href="/principal-principal" style="padding-top: 0px;">
        <img src="/assets/img/logo/logo-paroquia1.png" height="50" width="60"/>
    </a>
</div>

<div class="collapse navbar-collapse">

    <?= $this->navigation('navigation')
        ->setAcl($this->acl)
        ->setRole($this->role)
        ->menu()
        ->setPartial(array('partials/menu.phtml', 'default'))
        ->render(); ?>

    <?php if ($this->Auth()) { ?>

        <ul class="nav navbar-nav">
            <li class="active"><a href="/principal-principal">Home</a></li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Cadastros
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/frequencia_turma-frequenciaturma/frequencia">Frequência</a></li>
                    <li><a href="/catequizando-catequizando">Catequizando</a></li>
                    <li><a href="/responsavel-responsavel">Responsável Catequizando</a></li>
                    <li><a href="/catequista-catequista">Catequista</a></li>
<!--                    <li><a href="/frequencia_turma-frequenciaturma">Cadastro Frequência Turma</a></li>-->

                </ul>
            </li>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Relatórios
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/catequista-catequista/gerar-relatorio-pdf">Controle de Catequistas</a></li>
<!--                    <li><a href="#">Teste de PDF</a></li>-->
                </ul>
            </li>
            <?php
            #Alysson - Exibe este item de menu apenas para administradores
            if ($this->Auth()->id_perfil == TXT_CONST_PERFIL_ADMINISTRADOR) { ?>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        Configurações
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li><a href="/usuario-usuario">Usuários</a></li>
                        <li><a href="/perfil-perfil">Perfis</a></li>
                        <li class="divider"></li>
                        <li><a href="/permissao-permissao/cadastro">Gerenciador de Permissões</a></li>
                        <li><a href="/controller-controller">Cadastro Controller</a></li>
                        <li><a href="/action-action">Cadastro Action</a></li>
                    </ul>
                </li>
            <?php } ?>

            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Básicos
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/turma-turma">Turma</a></li>
                    <li><a href="/periodo_letivo-periodoletivo">Período Letivo</a></li>
                    <li><a href="/turma_catequizando-turmacatequizando">Enturmar Catequizandos</a></li>
                    <li><a href="/movimento_pastoral-movimentopastoral">Movimento Pastoral</a></li>
                    <li><a href="/etapa-etapa">Etapas</a></li>
                    <li class="divider"></li>
                    <li><a href="/turno-turno">Turno de aula</a></li>
                    <!--                    <li><a href="/responsavel_catequizando-responsavelcatequizando">Cadastro Responsável do Catequizando</a></li>-->
                    <li><a href="/sacramento-sacramento">Sacramento</a></li>
                    <li><a href="/paroquia-paroquia">Paróquia</a></li>
<!--                    <li><a href="/sacramento_catequizando-sacramentocatequizando">Cadastro Sacramento do Catequizando</a></li>-->
<!--                    <li><a href="/sacramento_responsavel-sacramentoresponsavel">Cadastro Sacramento do Responsável</a></li>-->
<!--                    <li><a href="/situacao_responsavel_catequizando-situacaoresponsavelcatequizando">Situação-->
<!--                            Responsável Catequizando</a></li>-->

                    <li><a href="/formacao-formacao">Formação Acadêmica</a></li>
                    <li><a href="/profissao-profissao">Profissão</a></li>
                    <li><a href="/grau_parentesco-grauparentesco">Grau de Parentesco</a></li>
                    <!--                    <li><a href="/estado_civil-estadocivil"> Estado Civil</a></li>-->
                    <li><a href="/situacao_conjugal-situacaoconjugal">Situação Conjugal</a></li>
<!--                    <li><a href="/situacao_responsavel-situacaoresponsavel">Cadastro Situação Responsável</a></li>-->

<!--                    <li class="divider"></li>-->
<!--                    <li><a href="/cidade-cidade">Cidades</a></li>-->
<!--                    <li><a href="/estado-estado">UF</a></li>-->

                </ul>
            </li>
        </ul>

        <?php if ($this->Auth()->id_perfil == TXT_CONST_PERFIL_ADMINISTRADOR) { ?>
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="/infra-infra" title="Botão para limpar as pastas Cache automaticamente.">
                        <span class="glyphicon glyphicon-ban-circle"></span> Limpar
                    </a>
                </li>
            </ul>
        <?php } ?>
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="/usuario-usuario">
                    <?= ucwords($this->Auth()->nm_usuario); ?>
                </a>
            </li>
            <li class="dropdown">
                <a href="<?= $this->url('logoff') ?>" title="Sair do Sistema">
                    <span class="glyphicon glyphicon-log-out"></span> Sair
                </a>
            </li>
        </ul>

    <?php } ?>
</div>

<!-- /.nav-collapse -->