<div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>

<!--    <a class="navbar-brand" href="/mcnetwork-index" style="padding-top: 0px;">-->
    <a class="navbar-brand" href="/principal-principal" style="padding-top: 0px;">
        <img src="/assets/img/logo/logo-menu.png" height="50" width="180" />
    </a>
</div>

<div class="collapse navbar-collapse">

    <?= $this->navigation('navigation')
            ->setAcl($this->acl)
            ->setRole($this->role)
            ->menu()
            ->setPartial(array('partials/menu.phtml', 'default'))
            ->render(); ?>

    <?php if ($this->Auth()) { ?>

    <ul class="nav navbar-nav">
        <li class="active"><a href="/principal-principal">Home</a></li>
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Cadastros
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="/formacao-formacao">Cad. Formaçao Academica</a></li>
                <li><a href="/catequista-catequista">Cad. Catequista</a></li>
                <li><a href="/turma-turma">Cad. Turma</a></li>
                <li><a href="/turno-turno">Cad. Turno</a></li>
                <li><a href="/turma_catequisando-turmacatequisando">Enturmar Catequisandos</a></li>
                <li><a href="/situacao_conjugal-situacaoconjugal">Cad Situação Conjugal</a></li>
                <li><a href="/profissao-profissao">Cad Profissão</a></li>
                <li><a href="/situacao_responsavel-situacaoresponsavel">Cad Situação Responsável</a></li>
                <li class="divider"></li>
                <li><a href="/graduacao-graduacao">Graduações - Modelo</a></li>
                <li><a href="/atleta-atleta">Atletas - Modelo</a></li>
                <li><a href="/academia-academia">Academias - Modelo</a></li>
                <li><a href="/evento-evento">Competições - Modelo</a></li>
                <li><a href="/inscricoes_evento-inscricoesevento">Realizar Inscriçoes - Modelo</a></li>

            </ul>
        </li>
        <li><a href="#">Relatórios</a></li>
        <?php
        #Alysson - Exibe este item de menu apenas para administradores
        if ($this->Auth()->id_perfil == TXT_CONST_PERFIL_ADMINISTRADOR) { ?>
            <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    Configurações
                    <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="/permissao-permissao/cadastro">Gerenciador de Permissões</a></li>
                    <li><a href="/controller-controller">Cad. Controller</a></li>
                    <li><a href="/action-action">Cad. Action</a></li>
                    <li class="divider"></li>
                    <li><a href="/detalhes_regras_luta-detalhesregrasluta">Configuração das Regras de Luta - Modelo</a></li>
                </ul>
            </li>
        <?php } ?>

        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Básicos
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="/etapa-etapa">Cadastro de Etapas</a></li>
                <li><a href="/grau_parentesco-grauparentesco">Cadastro de Grau de Parentesco</a></li>
                <li><a href="/responsavel_catequisando-responsavelcatequisando">Cadastro de Responsaveis</a></li>
                <li><a href="/paroquia-paroquia">Cadastro de Paroquia</a></li>
                <li><a href="/periodo_letivo-periodoletivo">Periodo Letivo</a></li>
                <li><a href="/sacramento-sacramento">Sacramento</a></li>
                <li><a href="/sacramento_catequisando-sacramentocatequisando">Cad. Sacramento Catequisando</a></li>
                <li><a href="/movimento_pastoral-movimentopastoral">Movimento Pastoral</a></li>
                <li class="divider"></li>
                <li><a href="/usuario-usuario">Usuários</a></li>
                <li><a href="/perfil-perfil">Perfis</a></li>
                <li class="divider"></li>
                <li><a href="/cidade-cidade">Cidades</a></li>
                <li><a href="/estado-estado">UF</a></li>
            </ul>
        </li>

    </ul>

    <?php if ($this->Auth()->id_perfil == TXT_CONST_PERFIL_ADMINISTRADOR) { ?>
        <ul class="nav navbar-nav navbar-right">
            <li>
                <a href="/infra-infra" title="Botão para limpar as pastas Cache automaticamente.">
                    <span class="glyphicon glyphicon-ban-circle"></span> Limpar
                </a>
            </li>
        </ul>
    <?php } ?>
    <ul class="nav navbar-nav navbar-right">
        <li>
            <a href="/usuario-usuario">
                <?= ucwords($this->Auth()->nm_usuario); ?>
            </a>
        </li>
        <li class="dropdown">
            <a href="<?= $this->url('logoff')?>" title="Sair do Sistema">
                <span class="glyphicon glyphicon-log-out"></span> Sair
            </a>
        </li>
    </ul>

    <?php } ?>
</div>

<!-- /.nav-collapse -->