<div class="page-head">
    <h2>Adicionar Aluno</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
                <?php
                $form->setAttribute('action', $this->url('navegacao', array('controller'=>$controller,'action' => 'gravar')));
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('data-role', 'form');
                $form->prepare();
                echo $this->form()->openTag($form);
                $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue()));

                echo $this->formHidden($form->get('id'));

                $form->get('dt_nascimento')->setValue(Estrutura\Helpers\Data::converterDataBancoMySQL2Brazil($form->get('dt_nascimento')->getValue()));

                ?>
                <!--DADOS PESSOAIS -->
                <fieldset>
                    <div class="container">
                        <div class="row">
                            <div class="col-md-5 col-md-push-1">

                                <div class="form-group">
                                    <div class="col-md-12">
                                        <?= $this->formRow($form->get('nm_catequisando')) ?>
                                    </div>
                                </div>
                                    <div class="form-group">
                                        <div class="col-md-6">
                                            <?= $this->formRow($form->get('id_sexo')) ?>
                                        </div>
                                   </div>
                              <div class="col-md-5">
                                   <div class="form-group">
                                       <?= $this->formRow($form->get('id_telefone_residencial')) ?>
                                   </div>
                               </div>
                                   <div class="col-md-5 col-md-push-1">
                                       <div class="form-group">
                                           <?= $this->formRow($form->get('id_telefone_celular')) ?>
                                       </div>
                                   </div>
                               </div><!-- TERMINA AQUI-->

                            <div class="col-md-4 col-md-push-2">
                                <div class="form-group">
                                    <div class="col-md-12">
                                        <?=$this->formRow($form->get('dt_nascimento'))?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-12">
                                        <?=$this->formRow($form->get('em_email'))?>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-md-12">
                                        <?=$this->formRow($form->get('id_endereco'))?>
                                    </div>
                                </div>
                            </div>
                            </div>
                        </div>
                </fieldset><!-- FIM DADOS PESSOAIS -->

                <fieldset>
                    <div class="form-group">
                        <div class="col-md-4 col-md-push-1">
                            <?=$this->formRow($form->get('cs_necessidade_especial'))?>
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-4 col-md-push-1">
                            <?=$this->formRow($form->get('cs_estudante'))?>
                        </div>
                    </div>
                </fieldset>

                </div>
                <div class="form-group">
                    <div class="col-md-10">
                        <button type="submit" class="btn btn-primary">Salvar</button>
                        <a href="<?=$this->url('navegacao', ['controller'=>$controller])?>" class="btn btn-default">Voltar</a>
                    </div>
                </div>
                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function() {
        $( "#dt_nascimento" ).datepicker(
            { dateFormat: 'dd/mm/yy' }
        );

        $( "input#id_academia" ).autocomplete({
            minLength: 3,
            source: "/academia-academia/autocompleteacademia"
        });

        $( "input#id_cidade" ).autocomplete({
            minLength: 4,
            source: "/cidade-cidade/autocompletecidade"
        });
    });
</script>