<link rel="stylesheet" type="text/css" href="/assets/css/bootstrap-datetimepicker.min.css">

<div class="row row-offcanvas row-offcanvas-right">
    <div class="col-xs-12 col-sm-9">
        <div class="well">
            <div class="page-head">
                <h2>Cadastro Estado Civil</h2>
            </div>

            <?php
            $form->setAttribute('action', $this->url('navegacao', array('controller' => $controller, 'action' => 'gravar')));
            $form->setAttribute('class', 'form-horizontal');
            $form->setAttribute('method', 'post');
            $form->setAttribute('data-role', 'form');
            $form->prepare();
            echo $this->form()->openTag($form);

            $form->get('id')->setValue(Estrutura\Helpers\Cript::enc($form->get('id')->getValue()));

            echo $this->formHidden($form->get('id'));
            ?>

            <div class="form-group">
                <div class="col-md-4">
                    <?=$this->formRow($form->get('nm_estado_civil'))?>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-7">
                    <button type="submit" class="btn btn-primary">Salvar</button>
                    <a href="<?= $this->url('navegacao', ['controller' => $controller]) ?>" class="btn btn-default">Voltar</a>

                </div>
            </div>
            <?= $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
<script type="text/javascript"
        src="/assets/compact-js/moment.js,bootstrap-datetimepicker.min.js,validator.min.js,jquery.mask.min.js,jquery.complexify.js,usuario|usuario|cadastro.js">

</script>