<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<div class="page-head">
    <h2>Lista Estado Civil</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default"
               href="<?= $this->url('navegacao', array('controller' => $controller, 'action' => 'cadastro')) ?>"
               title="Novo Estado Civil">Novo Estado Civil</a>
        </div>
    </div>
    <br/>
    <div class="row" id="estado-civil"></div>
</div>

<script>
    // funcao ajax para buscar a paginacao
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/estado_civil-estadocivil/index-pagination',
            async: true,
            data: {},
            beforeSend: function () {

                $('#estado-civil').html(
                    '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                );
            },
            success: function (data) {

                $('#estado-civil').html(data);
            }
        });

    })
</script>
