<div class="page-head">
    <h2>Cadastro Período Letivo</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="block-flat">
            <div class="content">
                <fieldset>
                    <legend>Dados do Período Letivo</legend>
                    <?php if (isset($dadosPeriodoLetivo) && $dadosPeriodoLetivo) { ?>
                        <div class="bs-callout bs-callout-primary">
                            <ul class="primary">
                                <li><b>Código Período:</b> <?= $dadosPeriodoLetivo->getId() ?></li>
                                <li><b>Período Letivo:</b> <?= $dadosPeriodoLetivo->getDtAnoLetivo() ?></li>
                                <li><b>Data de
                                        Início:</b> <?= Estrutura\Helpers\Data::converterDataBancoMySQL2Brazil($dadosPeriodoLetivo->getDtInicio()) ?>
                                </li>
                                <li><b>Data de
                                        Término:</b> <?= Estrutura\Helpers\Data::converterDataBancoMySQL2Brazil($dadosPeriodoLetivo->getDtFim()) ?>
                                </li>
                            </ul>
                        </div>
                    <?php } ?>
                </fieldset>
                <?php
                $form->setAttribute('action', '#');
                $form->setAttribute('class', 'form-horizontal');
                $form->setAttribute('method', 'post');
                $form->setAttribute('data-role', 'form');
                /* echo '<pre>';
                 print_r($dadosPeriodoLetivo);
                 echo '</pre>';*/
                $form->prepare();
                echo $this->form()->openTag($form);
                $form->get('id')->setValue($dadosPeriodoLetivo->getId());
                $form->get('dt_encontro')->setValue(Estrutura\Helpers\Data::converterDataBancoMySQL2Brazil($form->get('dt_encontro')->getValue()));
                echo $this->formHidden($form->get('id'));
                ?>

                <fieldset>
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-1"></div>

                            <div class="col-sm-2">
                                <div class="form form-group" id="datetimepicker">
                                    <?= $this->formRow($form->get('dt_encontro')); ?>
                                </div>
                            </div>
                            <div class="col-sm-1"></div>
                            <div class="col-sm-2">
                                <a style="margin-top: 25px;" id="adicionar" class="btn btn-primary" href="#"
                                   title="Adicionar data do encontro">Adicionar Encontro</a>
                            </div>
                        </div>
                    </div>
                </fieldset>

                <?= $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
    <div class="row" id="periodoletivodetalhe-pagination"></div>
</div>
<script type="text/javascript"
        src="/assets/compact-js/moment.js,bootstrap-datetimepicker.min.js,validator.min.js,jquery.mask.min.js,jquery.complexify.js,usuario|usuario|cadastro.js"></script>
<script type="text/javascript" language="javascript" class="init">
    $(document).ready(function () {
        $("#dt_encontro").datepicker(
            {dateFormat: 'dd/mm/yy'}
        );

        //Função que faz a listagem ser paginada.
        function carregarGridPaginadaAjax() {
            $.ajax({
                type: "post",
                dataType: "text",
                cache: false,
                url: '/periodo_letivo-periodoletivo/detalhe-pagination',
                async: true,
                data: {id_periodo_letivo: <?=$dadosPeriodoLetivo->getId()?>},
                beforeSend: function () {
                    $('#periodoletivodetalhe-pagination').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                    );
                },
                success: function (data) {
                    $('#periodoletivodetalhe-pagination').html(data);
                }
            });
        }

        carregarGridPaginadaAjax(); //Chama a Paginação da listagem

        /*Função Ajax que adiciona os encontros ao Banco de dados*/
        $('#adicionar').click(function () {
            var dados = $('#detalheperiodoletivoform').serialize();
            $.ajax({
                type: 'POST',
                dataType: 'json',
                url: '/periodo_letivo-periodoletivo/adicionarperiodoletivodetalhe',
                async: true,
                data: dados,
                success: function (response) {
                    $("#dt_encontro").val("");
                    if (response.sucesso == true) {
                        carregarGridPaginadaAjax();
                    }
                }
            });

            return false;
        });

    });
</script>
