<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<div class="col-md-12">
    <div class="alert alert-danger alert-dismissable" id="msg" style="display: none;">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>Error!</strong> <span id="msg-info"></span>
    </div>
    <div class="table-responsive">
        <table class="table table-striped" id="tablesorterFrequencia" >
            <thead>
            <tr>

                <th class="text-center">Nome Catequizando</th>
                <?php  foreach($encontros as $encontro): ?>
                    <th class="text-center"><?=$encontro['dt_encontro']?></th>
                <?php endforeach; ?>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <th class="text-center">Nome Catequizando</th>
                <?php  foreach($encontros as $encontro): ?>
                    <th class="text-center"><?=null?></th>
                <?php endforeach; ?>
            </tr>


            </tfoot>
                <tbody class="">
                <tr role="row" class="tablesorter-filter-row" align="center">

                </tr>
                <?php foreach ($lista as $item): #xd($item) ?>
                    <tr>
                        <td><?= $item['nm_catequizando']?></td>
                        <?php  foreach($encontros as $encontro): ?>
                            <td align="center"><input type="checkbox" value="<?= $item['id_turma_catequizado']."_".$encontro['id_detalhe_periodo_letivo']?>" class="falta"></td>
                        <?php endforeach; ?>

                    </tr>
                    <?php endforeach; ?>
                </tbody>


        </table>

        <div class="row">
            <div class="col-md-12">
                <div class="col-md-2">
                    <a href="<?= $this->url('navegacao', ['controller' => 'principal-principal']) ?>" class="btn btn-primary" title="Retorna para a Página Principal">Home</a>
                </div>
                <div class="col-md-2 col-md-push-9">
                    <button id="gravar" class="btn btn-primary">Gravar</button>
                </div>

            </div>
        </div>

    </div>
</div>

<!-- MODAL -->
<div class="modal fade carregando" role="dialog" id="myModal">
    <div class="modal-dialog" style="width: 200px; height: 200px;">
        <div class="modal-content">
            <div class="">
                <p><img class="img-responsive"  src="/assets/img/carregando5.gif"><p>
            </div>
        </div>
    </div>
</div>
<!--<script src="/assets/compact-js/moment.js,validator.min.js,jquery.mask.min.js,jquery.ui.widget.js,jquery.tablesorter.js,jquery.tablesorter.widgets.js,jquery.tablesorter.pager.js" type="text/javascript"></script>-->
<script src="/assets/js/moment.js" type="text/javascript"></script>
<script src="/assets/js/validator.min.js" type="text/javascript"></script>
<script src="/assets/js/jquery.mask.min.js" type="text/javascript"></script>
<script src="/assets/js/jquery.ui.widget.js" type="text/javascript"></script>
<script src="/assets/js/jquery.tablesorter.js" type="text/javascript"></script>
<script src="/assets/js/jquery.tablesorter.widgets.js" type="text/javascript"></script>
<script src="/assets/js/jquery.tablesorter.pager.js" type="text/javascript"></script>

<script type="text/javascript" language="javascript" >
    $(function () {
            // Alert de erro...

            $("#gravar").on('click',function(){
                var faltas = new Array();

                $("input.falta[type=checkbox]:checked").each(function(){
                    faltas.push($(this).val());
                });

                $.ajax({
                    type:'post',
                    dataType:'json',
                    url:'/frequencia_turma-frequenciaturma/gravar-presenca',
                    cache:false,
                    async:true,
                    data:{
                        form:faltas
                    },

                    beforeSend: function(){
                            $("#myModal").modal('show');
                    },

                    success : function(response){
                        $("#myModal").modal('hide');

                        if(response.sucesso == true){
                            window.location ='/frequencia_turma-frequenciaturma';
                        }else{
                            $('#msg-info').html(response.msg);
                            $('#msg').fadeIn('slow');
                        }
                    }

                });
            });

        // NOTE: $.tablesorter.theme.bootstrap is ALREADY INCLUDED in the jquery.tablesorter.widgets.js
        // file; it is included here to show how you can modify the default classes
        $.tablesorter.themes.bootstrap = {
            // these classes are added to the table. To see other table classes available,
            // look here: http://getbootstrap.com/css/#tables
            table: 'table table-bordered',
            caption: 'caption',
            header: 'bootstrap-header', // give the header a gradient background
            footerRow: '',
            footerCells: '',
            icons: '', // add "icon-white" to make them white; this icon class is added to the <i> in the header
            sortNone: 'bootstrap-icon-unsorted',
            sortAsc: 'icon-chevron-up glyphicon glyphicon-chevron-up', // includes classes for Bootstrap v2 & v3
            sortDesc: 'icon-chevron-down glyphicon glyphicon-chevron-down', // includes classes for Bootstrap v2 & v3
            active: '', // applied when column is sorted
            hover: '', // use custom css here - bootstrap class may not override it
            filterRow: '', // filter row class
            even: '', // odd row zebra striping
            odd: ''  // even row zebra striping
        };

        // call the tablesorter plugin and apply the uitheme widget
        $("#tablesorterFrequencia").tablesorter({
            // this will apply the bootstrap theme if "uitheme" widget is included
            // the widgetOptions.uitheme is no longer required to be set
            theme: "bootstrap",
            widthFixed: true,
            headerTemplate: '{content} {icon}', // new in v2.7. Needed to add the bootstrap icon!

            // widget code contained in the jquery.tablesorter.widgets.js file
            // use the zebra stripe widget if you plan on hiding any rows (filter widget)
            widgets: ["uitheme", "zebra"],
            widgetOptions: {
                // using the default zebra striping class name, so it actually isn't included in the theme variable above
                // this is ONLY needed for bootstrap theming if you are using the filter widget, because rows are hidden
                zebra: ["even", "odd"],
                // reset filters button
                filter_reset: ".reset"

                // set the uitheme widget to use the bootstrap theme class names
                // this is no longer required, if theme is set
                // ,uitheme : "bootstrap"

            },
            headers: {
                5: {sorter: false}
            }
        });


    });
</script>