<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<?php
/** @var $form \CategoriaPeso\Form\CategoriaPeso */
/** @var $lista \CategoriaPeso\Service\CategoriaPeso[] */

?>

<div class="page-head">
    <h2>Categoria Peso</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12">
            <a class="btn btn-default" href="<?=$this->url('navegacao',array('controller'=>$controller,'action'=>'cadastro'))?>" title="Nova categoria de Peso">Nova Categoria</a>
        </div>
    </div>
    <br />
    <div class="row" id="categoria-peso"></div>    
</div>

<script>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/categoria_peso-categoriapeso/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#categoria-peso').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                        );
            },
            success: function (data) {

                $('#categoria-peso').html(data);
            }
        });

    })
</script>
