<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<!--<link rel="stylesheet" href="/assets/css/jquery.tablesorter.theme.bootstrap.css">-->
<!--<link rel="stylesheet" href="/assets/css/jquery.tablesorter.pager.css">-->


<?php
/** @var $form \Atleta\Form\Atleta */
/** @var $lista \Atleta\Service\Atleta[] */
?>
<div class="page-head">
    <h2>Lista de Perfis</h2>
</div>
<div class="cl-mcont">
    <div class="row">
        <div class="col-md-12"><?php // botao novo atleta?>
            <a class="btn btn-default" href="<?= $this->url('navegacao', array('controller' => $controller, 'action' => 'cadastro')) ?>" title="Adiciona um novo perfil">Novo Perfil</a>
        </div>
    </div>
    <br />
    <div class="row" id="atleta-pagination"></div>    
</div>

<script>
    <?php // funcao ajax para buscar a paginacao?>
    $(function () {

        $.ajax({
            type: "post",
            dataType: "text",
            cache: false,
            url: '/perfil-perfil/index-pagination',
            async: true,
            data: {
            },
            beforeSend: function () {

                $('#atleta-pagination').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                        );
            },
            success: function (data) {

                $('#atleta-pagination').html(data);
            }
        });

    })
</script>
