<link rel="stylesheet" href="/assets/compact-css/jquery.tablesorter.theme.bootstrap.css,jquery.tablesorter.pager.css">

<div class="col-md-12">
    <div class="table-responsive">
        <table class="table table-striped" id="tablesorterAtletas">
            <thead>
            <tr>
                <th class="text-center" style="width: 5%;">Código</th>
                <th class="text-center">Nome</th>
                <th class="text-center">Telefone Residencial</th>
                <th class="text-center">Telefone Celular</th>
                <th class="text-center">E-mail</th>
                <th class="text-center">Profissão</th>
                <th class="text-center">Responsável Por</th>
                <th class="text-center" style="width: 15%;">Ações</th>
            </tr>
            </thead>
            <tfoot>
            <tr>
                <th class="text-center" style="width: 5%;">Código</th>
                <th class="text-center">Nome</th>
                <th class="text-center">Telefone Residencial</th>
                <th class="text-center">Telefone Celular</th>
                <th class="text-center">E-mail</th>
                <th class="text-center">Profissão</th>
                <th class="text-center">Responsável Por</th>
                <th class="text-center" style="width: 15%;">Ações</th>

            </tr>
            <tr>
                <th colspan="8" class="ts-pager form-horizontal">
                    <?php
                    echo $this->paginationControl(
                        $paginator, 'Sliding', 'partials/pagination.phtml', [
                            'urlPagination' => '/responsavel-responsavel/index-pagination',
                            'countPerPage' => $countPerPage,
                            'divData' => '#atleta-pagination',
                        ]
                    );
                    ?>
                </th>
            </tr>
            </tfoot>
            <?php
            $numeroLinha = (($paginator->getCurrentPageNumber() - 1) * $paginator->getItemCountPerPage());
            if (!empty($paginator)) {
                ?>
                <tbody class="" align="center">
                <tr role="row" class="tablesorter-filter-row">
                    <?php
                    foreach ($camposFilter as $key => $campoFilter) {
                        ?>
                        <td>
                            <?php
                            if (!is_null($campoFilter)) {
                                ?>
                                <input type="search" placeholder="" class="col-md-12 tablesorter-filter"
                                       data-column="<?= $key ?>"
                                       value="<?= isset($filter[$key]) ? $filter[$key] : '' ?>">
                                <?php
                            } else {
                                ?>
                                &nbsp;
                                <?php
                            }
                            ?>
                        </td>
                        <?php
                    }
                    ?>
                </tr>
                <?php
                foreach ($paginator as $key => $responsavel) {

                    ?>
                    <tr>
                        <td class="text-center"><?= $responsavel['id_responsavel'] ?></td>
                        <td class="text-center"><?= \Estrutura\Helpers\String::nomeMaiusculo($responsavel['nm_responsavel']) ?></td>
                        <td class="text-center"><?= $service->getTelefone($responsavel['id_telefone_residencial']) ?></td>
                        <td class="text-center"><?= $service->getCelular($responsavel['id_telefone_celular']) ?></td>
                        <td class="text-center"><?= $responsavel['em_email'] ?></td>
                        <td class="text-center"><?= \Estrutura\Helpers\String::nomeMaiusculo($responsavel['nm_profissao']) ?></td>
                        <td class="text-center">
                            <button class="btn btn-default" data-toggle="modal" data-target="#modalCat"
                                    name="btn_verificar"
                                    value="<?= $responsavel['id_responsavel'] ?>"
                                    title="Verifica se é responsável por algum catequizando">Verificar
                            </button>
                        </td>
                        <td class="text-center">
                                <span class="btn-group">
                                    <?= \Estrutura\Service\HtmlHelper::botaoAlterar($this->url('navegacao', array('controller' => $controller, 'action' => 'cadastro', 'id' => Estrutura\Helpers\Cript::enc($responsavel['id_responsavel'])))) ?>
                                    <?= \Estrutura\Service\HtmlHelper::botaoExcluir($this->url('navegacao', array('controller' => $controller, 'action' => 'excluir', 'id' => Estrutura\Helpers\Cript::enc($responsavel['id_responsavel'])))) ?>
                                </span>
                        </td>
                    </tr>
                    <?php
                }
                ?>
                </tbody>
                <?php
            }
            ?>


            <div class="modal fade" id="modalCat" tabindex="-1" role="dialog" aria-labelledby="modalCatequizando">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                        aria-hidden="true">&times;</span></button>
                            <h4 class="modal-title" id="modalCatequizando">Responsável pelo(s) catequizando(s):</h4>
                        </div>
                        <div class="modal-body" id="lista_catequizando">
                            Carregando...
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-primary" data-dismiss="modal">Fechar</button>
                        </div>
                    </div>
                </div>
            </div>


        </table>
        <div class="row">
            <div class="col-md-12">
                <a href="<?= $this->url('navegacao', ['controller' => 'principal-principal']) ?>"
                   class="btn btn-primary" title="Retorna para a Página Principal">Início</a>
            </div>
        </div>
    </div>
</div>
<!--<script src="/assets/compact-js/moment.js,validator.min.js,jquery.mask.min.js,jquery.ui.widget.js,jquery.tablesorter.js,jquery.tablesorter.widgets.js,jquery.tablesorter.pager.js" type="text/javascript"></script>-->
<script src="/assets/js/moment.js" type="text/javascript"></script>
<script src="/assets/js/validator.min.js" type="text/javascript"></script>
<script src="/assets/js/jquery.mask.min.js" type="text/javascript"></script>
<script src="/assets/js/jquery.ui.widget.js" type="text/javascript"></script>
<script src="/assets/js/jquery.tablesorter.js" type="text/javascript"></script>
<script src="/assets/js/jquery.tablesorter.widgets.js" type="text/javascript"></script>
<script src="/assets/js/jquery.tablesorter.pager.js" type="text/javascript"></script>
<script type="text/javascript" language="javascript">
    $(function () {

        $("button[name='btn_verificar']").click(function () {
            $('#lista_catequizando').html("<h3>Carregando...</h3>");
            $.ajax({
                type: "post",
                dataType: "json",
                cache: false,
                url: '/responsavel-responsavel/recuperar-catequizando',
                async: true,
                data: {
                    id_responsavel: $(this).val()
                },
                success: function (data) {
                    var nomes_catequizandos = "<br>";
                    $.each(data , function(i, val) {
                        nomes_catequizandos += val;
                    });

                    $('#lista_catequizando').html(nomes_catequizandos);
                }
            });

        });

        // NOTE: $.tablesorter.theme.bootstrap is ALREADY INCLUDED in the jquery.tablesorter.widgets.js
        // file; it is included here to show how you can modify the default classes
        $.tablesorter.themes.bootstrap = {
            // these classes are added to the table. To see other table classes available,
            // look here: http://getbootstrap.com/css/#tables
            table: 'table table-bordered',
            caption: 'caption',
            header: 'bootstrap-header', // give the header a gradient background
            footerRow: '',
            footerCells: '',
            icons: '', // add "icon-white" to make them white; this icon class is added to the <i> in the header
            sortNone: 'bootstrap-icon-unsorted',
            sortAsc: 'icon-chevron-up glyphicon glyphicon-chevron-up', // includes classes for Bootstrap v2 & v3
            sortDesc: 'icon-chevron-down glyphicon glyphicon-chevron-down', // includes classes for Bootstrap v2 & v3
            active: '', // applied when column is sorted
            hover: '', // use custom css here - bootstrap class may not override it
            filterRow: '', // filter row class
            even: '', // odd row zebra striping
            odd: ''  // even row zebra striping
        };

        // call the tablesorter plugin and apply the uitheme widget
        $("#tablesorterAtletas").tablesorter({
            // this will apply the bootstrap theme if "uitheme" widget is included
            // the widgetOptions.uitheme is no longer required to be set
            theme: "bootstrap",
            widthFixed: true,
            headerTemplate: '{content} {icon}', // new in v2.7. Needed to add the bootstrap icon!

            // widget code contained in the jquery.tablesorter.widgets.js file
            // use the zebra stripe widget if you plan on hiding any rows (filter widget)
            widgets: ["uitheme", "zebra"],
            widgetOptions: {
                // using the default zebra striping class name, so it actually isn't included in the theme variable above
                // this is ONLY needed for bootstrap theming if you are using the filter widget, because rows are hidden
                zebra: ["even", "odd"],
                // reset filters button
                filter_reset: ".reset"

                // set the uitheme widget to use the bootstrap theme class names
                // this is no longer required, if theme is set
                // ,uitheme : "bootstrap"

            },
            headers: {
                5: {sorter: false}
            }
        });

        $('#filtrarRelatorioSaquesPagos').click(function () {

            $.ajax({
                type: "post",
                dataType: "text",
                cache: false,
                url: '/mcnetwork-relatorio/relatorio-saques-pagos',
                async: true,
                data: {
                    dt_inicio: $('#dt_inicio').val(),
                    dt_fim: $('#dt_fim').val()
                },
                beforeSend: function () {

                    $('#modal-relatorio-body-3').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                    );
                },
                success: function (data) {

                    $('#modal-relatorio-body-3').html(data);
                }
            });
        });


        $('.relatorio-recusar-recibo').off('click').on('click', function () {

            var idPagamento = $(this).attr('rel');

            $.ajax({
                type: "post",
                dataType: "text",
                cache: false,
                url: '/pagamento-pagamento/recusar-recibo',
                async: true,
                beforeSend: function () {

                    $('#modal-relatorio-body-3').html(
                        '<div class="row"><div class="col-md-12 text-center"><p><img src="/assets/img/carregando.gif"><p></div></div>'
                    );
                },
                data: {
                    id_saque: idPagamento
                },
                success: function () {

                    $.ajax({
                        type: "post",
                        dataType: "text",
                        cache: false,
                        url: '/mcnetwork-relatorio/relatorio-saques-pagos',
                        async: true,
                        data: {},
                        success: function (data) {

                            $('#modal-relatorio-body-3').html(data);
                        }
                    });
                }
            });
        });

        $("#imprimirRelatorioSaquesPagos").click(function () {

            var modalPrint = $('.modalPrint');
            modalPrint.removeClass('modal');
            $('.form-inline').hide();
            $('#printSection').addClass('printSection');
            $('#printSection').html(modalPrint.html());
            window.print();
            modalPrint.addClass('modal');
            $('.form-inline').show();
            $('#printSection').removeClass('printSection');
            $('#printSection').html('');
        });
    });
</script>